@api = http://localhost:5000

# --- REPOS --- #

### Get repos from api
POST {{api}}/repos
Content-Type: application/json

{
    "owner": "mauvies",
    "page": 3
}

# --- FAVORITE REPOS --- #

### Get favorites
GET {{api}}/favorites

### Add repo to favorites
POST {{api}}/favorites  
Content-Type: application/json

{
    "id": "367436552"
}

### Delete repo
DELETE {{api}}/favorites/363411910
