@api = http://localhost:5000

# --- REPOS --- #

### Get repos from api
GET {{api}}/repos
Content-Type: application/json

{
    "owner": "trioteca"
}

# --- FAVORITE REPOS --- #

### Get favorites
GET {{api}}/favorites
Content-Type: application/json

### Add repo to favorites
POST {{api}}/favorites  
Content-Type: application/json

{
    "id": "337654669"
}

### Delete repo
DELETE {{api}}/favorites/363411910
