@api = http://localhost:5000

# --- FAVORITE REPOS --- #

### Get favorites
GET {{api}}/favorites
Content-Type: application/json

### Add repo to favorites
POST {{api}}/favorites  
Content-Type: application/json

{
    "id": "363411910"
}

### Delete repo
DELETE {{api}}/favorites/363411910
