version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - '27015:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  api:
    container_name: back-container
    build:
      context: ../repo-zoom-api
    image: mauvies/repo-zoom:backend
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  frontend:
    container_name: front-container
    build: ../repo-zoom-frontend
    image: mauvies/repo-zoom:frontend
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
